image: node:latest
stages:
    - build
    - test
    - deploy

cache:
    paths:
        - dist/
        - node_modules/

build:
    stage: build
    script:
        - npm install
        - npm run build

testing_testing:
    stage: test
    script:
        - npm test

deploy_release:
    stage: deploy
    script:
        - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh

        - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
        - scp -r -P $DEPLOY_PORT ./dist/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
        - ssh $DEPLOY_USER@$DEPLOY_HOST  -P $DEPLOY_PORT cd $DEPLOY_PATH; npm install
#    only:
#        - tags
